config/routes.rb
Finalproject::Application.routes.draw do
  resources :users
  root :to => 'home#index'
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/signup',  to: 'users#new'

  match '/collection', to: 'collection#index'
  match '/checkout', to: 'checkout#index'
  match '/thankyou', to: 'thankyou#index'
  match '/about', to: 'about#index'
  match '/black', to: 'black#index'
  match '/brown', to: 'brown#index'
  match '/monk', to: 'monk#index'
  match '/customize', to: 'customize#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation	
  before_save { |user| user.email = email.downcase }
  has_secure_password
  before_save :create_remember_token


  #paper clip
  attr_accessible :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/missing.png"
  

  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, email: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  after_validation { self.errors.messages.delete(:password_digest) }
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/black_controller.rb
class BlackController < ApplicationController
  def index
  end
end

app/controllers/brown_controller.rb
class BrownController < ApplicationController
  def index
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/monk_controller.rb
class MonkController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
  	user = User.find_by_email(params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  	   sign_in user
       flash[:success] = "Welcome Back!"
       redirect_to user
  	else
  		@message = "Invalid email/password combination"
  		render 'new'
  	end
  end

  def destroy
  	sign_out
    redirect_to root_url
  end
end

app/controllers/thankyou_controller.rb
class ThankyouController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome To Mink!"
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
       sign_in @user
       redirect_to @user
    else
      render 'edit'
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/black_helper.rb
module BlackHelper
end

app/helpers/brown_helper.rb
module BrownHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/collection_helper.rb
module CollectionHelper
end

app/helpers/customize_helper.rb
module CustomizeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/monk_helper.rb
module MonkHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    	cookies.permanent[:remember_token] = user.remember_token
    	self.current_user = user
  	end

  	def current_user=(user)
    	@current_user = user
  	end

  	def signed_in?
    	!current_user.nil?
  	end

  	def current_user
    	@current_user ||= User.find_by_remember_token(cookies[:remember_token])
  	end

  	def sign_out
    	self.current_user = nil
    	cookies.delete(:remember_token)
  	end
end

app/helpers/thankyou_helper.rb
module ThankyouHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<%= render "shared/nav_form" %>
<div class="about_container">
   <div class="about_content">
          <h1 class="about_header"> ABOUT US </h1>
    </div>
          <hr>
          <div id="bottom_wrapper">
              <div class="row-fluid">
                <div class="span4">
                    <h2 class="about">CHOOSE YOUR DESIGN</h2>
                    <img src="/assets/choosestyle.png" class="align-center medium" >
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                </div>
                <div class="span4">
                  <h2 class="about">MEASURE & CUSTOMIZE</h2>
                  <img src="/assets/customize.png" class="align-center medium" >
                  
                  <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                </div>
                <div class="span4">
                  <h2 class="about"s>FREE SHIPPING & ALTERATION</h2>
                  <img src="/assets/freestuff.png" class="align-center medium" >
                  <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
                </div>
              </div>
           </div>
 </div>

app/views/black/index.html.erb
<%= render "shared/nav_form" %>
      <div class="product_container">
          <div class="product_content">
            <span class='zoom' id='ex1'>
                <img src='/assets/blackoxford_big.jpg' width='450' alt='Black Oxford'/>
            </span>
            <div class="product_des">
                    <br>
                    <p> Description: With its hand-beveled waist, fine punching on the toe cap and rounded soles, the City II has many of the bespoke elements that characterise the Prestige collection. </p>
                    <br>
                    <p> Leather &amp Color: Black Oxford Calf</p>
            </div>
          </div>
          <div class="product_shop">
                  <h2 class="product_title"> City II</h2>
                  <p class="product_price"> $300 </p>
                  <p align="center"><%= link_to "CUSTOMIZE NOW", customize_path, class: "customize_button" %></p>
          </div>
          <div class="product_other">
                <hr class="divider">
                <h2 class="suggestion"> you might also like </h2>
                <ul class="other">
                  <li>
                        <a href="brown.html">
                            <img src="/assets/brownoxford_1.png" width="300"> 
                            <figcaption class="fig"> Philip II </figcaption>
                        </a>
                  </li>

                  <li>
                        <a href="monk.html">
                          <img src="/assets/buckles_1.png" width="300">
                           <figcaption class="fig"> Chapel </figcaption>
                        </a>
                  </li>
                </ul>
          </div>
      </div>

app/views/checkout/index.html.erb
<%= render "shared/nav_form" %>
      <div class="checkout">
          <form id="checkout_form">
            <fieldset class="shippinginfo">
              <h5>SHIPPING INFO</h5>
            <p>
              <label for="name">Email</label>
              <input name="name" type="text" class="text" id="name" tabindex="100" />
            </p>
            <p>
              <label for="name">Name</label>
              <input name="name" type="text" class="text" id="name" tabindex="100" />
            </p>
            <p>
              <label for="address">Address</label>
              <input name="address" type="text" class="text" id="address" tabindex="140" />
            </p>
            <p>
              <label for="address">City</label>
              <input name="address" type="text" class="text" id="address" tabindex="140" />
            </p>
            <p>
              <label for="state">State</label>
              <select name="state" id="state" tabindex="150">
                <option value="AL">Alabama</option>
                <option value="AK">Alaska</option>
                <option value="AZ">Arizona</option>
                <option value="AR">Arkansas</option>
                <option value="CA">California</option>
                <option value="CO">Colorado</option>
                <option value="CT">Connecticut</option>
                <option value="DE">Delaware</option>
                <option value="DC">District of Columbia</option>
                <option value="FL">Florida</option>
                <option value="GA">Georgia</option>
                <option value="HI">Hawaii</option>
                <option value="ID">Idaho</option>
                <option value="IL">Illinois</option>
                <option value="IN">Indiana</option>
                <option value="IA">Iowa</option>
                <option value="KA">Kansas</option>
                <option value="KY">Kentucky</option>
                <option value="LA">Louisiana</option>
                <option value="ME">Maine</option>
                <option value="MD">Maryland</option>
                <option value="MA">Massachusetts</option>
                <option value="MI">Michigan</option>
                <option value="MN">Minnesota</option>
                <option value="MO">Missouri</option>
                <option value="MT">Montana</option>
                <option value="NE">Nebraska</option>
                <option value="NV">Nevada</option>
                <option value="NH">New Hampshire</option>
                <option value="NJ">New Jersey</option>
                <option value="NM">New Mexico</option>
                <option value="NY">New York</option>
                <option value="NC">North Carolina</option>
                <option value="ND">North Dakota</option>
                <option value="OH">Ohio</option>
                <option value="OK">Oklahoma</option>
                <option value="OR">Oregon</option>
                <option value="PA">Pennsylvania</option>
                <option value="RI">Rhode Island</option>
                <option value="SC">South Carolina</option>
                <option value="SD">South Dakota</option>
                <option value="TN">Tennessee</option>
                <option value="TX">Texas</option>
                <option value="UT">Utah</option>
                <option value="VT">Vermont</option>
                <option value="VA">Virginia</option>
                <option value="WA">Washington</option>
                <option value="WV">West Virginia</option>
                <option value="WI">Wisconsin</option>
                <option value="WY">Wyoming</option>
              </select>
            </p>
            <p>
              <label for="zip">Zip Code</label>
              <input name="zip" type="text" class="text" id="zip" tabindex="160" />
            </p>
          </fieldset>

          <div class="checkout_item">
            <img src="/assets/brownoxford.png" class="item_img">
              <ul class="item_check"> 
                <li class="checked_item"> Brown Oxford  </li> <br>
                <li> Quantity: 1 </li>
                <li> Price: $300 </li>
                <li> Subtotal: $300 </li>
                <li> Tax: Pending </li>
                <li> Total: Pending </li>
              </ul>

          <div class="filler">
            <ul class="filler_info"> 
              <li> <strong> FREE SHIPPING </strong> </li>
              <li> All Mink orders include free global priority FedEx shipping. </li>
              <br>
              <li> <strong> OUR PROMISE </strong> </li>
              <li> If your order is anything less than what you expected, let us know and we will make it right.</li>
            </ul>
          </div>
      </div>
          <fieldset class="paymentinfo">
              <h5>PAYMENT INFO</h5>
            <p>
              <label for="state">TYPE</label>
              <select name="state" id="state" tabindex="150">
                <option value="WV">VISA</option>
                <option value="WI">MASTERCARD</option>
                <option value="WY">AMERICAN EXPRESS</option>
              </select>
            </p>
            <p>
              <label for="name">CARD NUMBER</label>
              <input name="name" type="text" class="text" id="cardnumber" tabindex="100" />
            </p>
            <p>
                <label for="address">EXP. MO</label>
                <input name="address" type="text" class="text" id="exp"  />
                <label for="address">EXP. YR</label>
                <input name="address" type="text" class="text" id="exp" />
            </p>
            <p>
              <label for="zip">CCV </label>
              <input name="zip" type="text" class="text" id="ccv" tabindex="160" />
            </p>
          </fieldset>

           <p class="billing_checkbox"> <input type="checkbox" name="billing" id="billing" tabindex="165" checked="checked"/> Billing address is the same as shipping address</p>

          <br>

          <fieldset id="billinginfo">
              <h5>BILLING INFO</h5>
            <p>
              <label for="name">Name</label>
              <input name="name" type="text" class="text" id="name" tabindex="100" />
            </p>
            <p>
              <label for="address">Address</label>
              <input name="address" type="text" class="text" id="address" tabindex="140" />
            </p>
            <p>
              <label for="address">City</label>
              <input name="address" type="text" class="text" id="address" tabindex="140" />
            </p>
            <p>
              <label for="state">State</label>
              <select name="state" id="state" tabindex="150">
                <option value="AL">Alabama</option>
                <option value="AK">Alaska</option>
                <option value="AZ">Arizona</option>
                <option value="AR">Arkansas</option>
                <option value="CA">California</option>
                <option value="CO">Colorado</option>
                <option value="CT">Connecticut</option>
                <option value="DE">Delaware</option>
                <option value="DC">District of Columbia</option>
                <option value="FL">Florida</option>
                <option value="GA">Georgia</option>
                <option value="HI">Hawaii</option>
                <option value="ID">Idaho</option>
                <option value="IL">Illinois</option>
                <option value="IN">Indiana</option>
                <option value="IA">Iowa</option>
                <option value="KA">Kansas</option>
                <option value="KY">Kentucky</option>
                <option value="LA">Louisiana</option>
                <option value="ME">Maine</option>
                <option value="MD">Maryland</option>
                <option value="MA">Massachusetts</option>
                <option value="MI">Michigan</option>
                <option value="MN">Minnesota</option>
                <option value="MO">Missouri</option>
                <option value="MT">Montana</option>
                <option value="NE">Nebraska</option>
                <option value="NV">Nevada</option>
                <option value="NH">New Hampshire</option>
                <option value="NJ">New Jersey</option>
                <option value="NM">New Mexico</option>
                <option value="NY">New York</option>
                <option value="NC">North Carolina</option>
                <option value="ND">North Dakota</option>
                <option value="OH">Ohio</option>
                <option value="OK">Oklahoma</option>
                <option value="OR">Oregon</option>
                <option value="PA">Pennsylvania</option>
                <option value="RI">Rhode Island</option>
                <option value="SC">South Carolina</option>
                <option value="SD">South Dakota</option>
                <option value="TN">Tennessee</option>
                <option value="TX">Texas</option>
                <option value="UT">Utah</option>
                <option value="VT">Vermont</option>
                <option value="VA">Virginia</option>
                <option value="WA">Washington</option>
                <option value="WV">West Virginia</option>
                <option value="WI">Wisconsin</option>
                <option value="WY">Wyoming</option>
              </select>
            </p>
            <p>
              <label for="zip">Zip Code</label>
              <input name="zip" type="text" class="text" id="zip" tabindex="160" />
            </p>
          </fieldset>
            <br><br>
            <a class="order" href="thankyou.html"> PlACE ORDER </a>
            <br><br>
        </form>
      </div>

app/views/home/index.html.erb
<%= render "/shared/nav_form" %>
          <div id="top_wrapper">
              <div class="home_content">
                  <div class="content_home">
                    <h1 class="home_header">MADE TO MEASURE SHOES </h1>
                    <%= link_to "CUSTOMIZE NOW", collection_path, class: "home_button" %>
                  </div> 
              </div>
            </div>
          <hr>
          <div id="bottom_wrapper">
              <div class="row-fluid">
                <div class="span4">
                    <h2 class="about">CHOOSE YOUR DESIGN</h2>
                    <img src="/assets/choosestyle.png" class="align-center medium" >
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                </div>
                <div class="span4">
                  <h2 class="about">MEASURE & CUSTOMIZE</h2>
                  <img src="/assets/customize.png" class="align-center medium" >
                  
                  <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                </div>
                <div class="span4">
                  <h2 class="about"s>FREE SHIPPING & ALTERATION</h2>
                  <img src="/assets/freestuff.png" class="align-center medium" >
                  <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
                </div>
              </div>
           </div> 

app/views/thankyou/index.html.erb
<%= render "/shared/nav_form" %>
        <div id="thankyou"> 
              <div class="message"> 
                  <h1> THANK YOU </h1>
                  <p> Your Order has been processed. We will send you a confirmation shortly. </p>
                  <%= link_to "Continue Shopping", root_path, class: "home_button" %> <br><br><br>
              </div>
        </div>