config/routes.rb
Finalproject::Application.routes.draw do
  resources :users
  root :to => 'home#index'
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/signup',  to: 'users#new'

  match '/collection', to: 'collection#index'
  match '/checkout', to: 'checkout#index'
  match '/thankyou', to: 'thankyou#index'
  match '/about', to: 'about#index'
  match '/black', to: 'black#index'
  match '/brown', to: 'brown#index'
  match '/monk', to: 'monk#index'
  match '/customize', to: 'customize#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation	
  before_save { |user| user.email = email.downcase }
  has_secure_password
  before_save :create_remember_token


  #paper clip
  attr_accessible :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/missing.png"
  

  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, email: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  after_validation { self.errors.messages.delete(:password_digest) }
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/black_controller.rb
class BlackController < ApplicationController
  def index
  end
end

app/controllers/brown_controller.rb
class BrownController < ApplicationController
  def index
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def index
  end
end

app/controllers/collection_controller.rb
class CollectionController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/monk_controller.rb
class MonkController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
  	user = User.find_by_email(params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  	   sign_in user
       flash[:success] = "Welcome Back!"
       redirect_to user
  	else
  		@message = "Invalid email/password combination"
  		render 'new'
  	end
  end

  def destroy
  	sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome To Mink!"
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
       sign_in @user
       redirect_to @user
    else
      render 'edit'
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/black_helper.rb
module BlackHelper
end

app/helpers/brown_helper.rb
module BrownHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/collection_helper.rb
module CollectionHelper
end

app/helpers/customize_helper.rb
module CustomizeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/monk_helper.rb
module MonkHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    	cookies.permanent[:remember_token] = user.remember_token
    	self.current_user = user
  	end

  	def current_user=(user)
    	@current_user = user
  	end

  	def signed_in?
    	!current_user.nil?
  	end

  	def current_user
    	@current_user ||= User.find_by_remember_token(cookies[:remember_token])
  	end

  	def sign_out
    	self.current_user = nil
    	cookies.delete(:remember_token)
  	end
end

app/helpers/thankyou_helper.rb
module ThankyouHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/collection/index.html.erb
<%= render "shared/nav_form" %>
          <div class="collection">
                <div class="collection_content">
                    <h1 class="collection_header">MODERN OXFORDS </h1>
                </div>
                <div class="view">
                    <img src="/assets/blackoxford.png" />
                        <div class="mask">
                            <h2><em> City II </em></h2>
                            <p> A modern Oxford with a traditional but delicate toe punch design, as well as decorative punching on the vamp and quarters. </p>
                            <p> $300 </p>
                            <%= link_to "SHOP NOW", black_path, class: "info" %>
                        </div>
                </div>    
                <hr>
                <div class="collection_content_1">
                    <h1 class="collection_header"> THE MONKSTRAP</h1>
                </div>
                <div class="view">
                      <img src="/assets/buckles.png" />
                          <div class="mask">
                              <h2><em> Chapel </em></h2>
                              <p> This flawless monkstrap is fashioned from a single piece of leather with no back seam, parallel buckles, squared toe and sweeping lines. </p>
                              <p> $300 </p>
                              <%= link_to "SHOP NOW", monk_path, class: "info" %>
                          </div>
                </div>    
                  <hr>
                  <div class="collection_content_2">
                      <h1 class="collection_header">CLASSIC BROGUE </h1>
                  </div>
                  <div class="view">
                      <img src="/assets/brownoxford.png" />
                          <div class="mask">
                              <h2><em>Philip II</em></h2>
                              <p> With its hand-beveled waist, fine punching on the toe cap and rounded soles, this classic brogue has many of the bespoke elements. </p>
                              <p> $300 </p>
                              <%= link_to "SHOP NOW", brown_path, class: "info" %>
                          </div>
                  </div>    
            </div>