config/routes.rb
Finalproject::Application.routes.draw do
  resources :users
  root :to => 'home#index'
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/signup',  to: 'users#new'

  match '/collection', to: 'collection#index'
  match '/checkout', to: 'checkout#index'
  match '/thankyou', to: 'thankyou#index'
  match '/about', to: 'about#index'
  match '/black', to: 'black#index'
  match '/brown', to: 'brown#index'
  match '/monk', to: 'monk#index'
  match '/customize', to: 'customize#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation	
  before_save { |user| user.email = email.downcase }
  has_secure_password
  before_save :create_remember_token


  #paper clip
  attr_accessible :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/missing.png"
  

  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, email: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  after_validation { self.errors.messages.delete(:password_digest) }
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/black_controller.rb
class BlackController < ApplicationController
  def index
  end
end

app/controllers/brown_controller.rb
class BrownController < ApplicationController
  def index
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/monk_controller.rb
class MonkController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome To Mink!"
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
       sign_in @user
       redirect_to @user
    else
      render 'edit'
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/black_helper.rb
module BlackHelper
end

app/helpers/brown_helper.rb
module BrownHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/collection_helper.rb
module CollectionHelper
end

app/helpers/customize_helper.rb
module CustomizeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/monk_helper.rb
module MonkHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    	cookies.permanent[:remember_token] = user.remember_token
    	self.current_user = user
  	end

  	def current_user=(user)
    	@current_user = user
  	end

  	def signed_in?
    	!current_user.nil?
  	end

  	def current_user
    	@current_user ||= User.find_by_remember_token(cookies[:remember_token])
  	end

  	def sign_out
    	self.current_user = nil
    	cookies.delete(:remember_token)
  	end
end

app/helpers/thankyou_helper.rb
module ThankyouHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MINK: Made-To-Measure Shoes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <ul class="nav">
            <li class="nav_brand"> <%= link_to "MINK", root_path, class: "selected" %></li>
            <li><%= link_to "COLLECTION", collection_path%></li>
            <li><%= link_to "ABOUT", about_path %></li>
        </ul>
        <% if signed_in? %>
            <ul id="login" class="nav">
                <li><%= link_to "PROFILE", user_path(current_user) %></li>
                <li><%= link_to "SETTINGS", edit_user_path(current_user) %></li>
                <li><%= link_to "SIGN OUT", signout_path, method: "delete" %></li>
                <li> <a href="#shoppingcart" role="button" data-toggle="modal"> SHOPPING CART </a></li>
            </ul>
        <% else %>
            <ul id="login" class="nav">
                <li><%= link_to "SIGN IN", signin_path %></li>
                <li><%= link_to "SIGN UP", signup_path %></li>
                <li> <a href="#shoppingcart" role="button" data-toggle="modal"> SHOPPING CART </a></li>
            </ul>
        <% end %>
    </div>
</div>
         <%= yield %>

          <hr class="divider">
      
          <div>
                <p class="footer_left">MINK</p>
                <p class="footer_right"> © 2013 Eric Lee </p> 
          </div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <ul class="nav">
            <li class="nav_brand"> <%= link_to "MINK", root_path, class: "selected" %></li>
            <li><%= link_to "COLLECTION", collection_path%></li>
            <li><%= link_to "ABOUT", about_path %></li>
        </ul>
        <% if signed_in? %>
            <ul id="login" class="nav">
                <li><%= link_to "PROFILE", user_path(current_user) %></li>
                <li><%= link_to "SETTINGS", '#' %></li>
                <li><%= link_to "SIGN OUT", signout_path, method: "delete" %></li>
                <li> <a href="#shoppingcart" role="button" data-toggle="modal"> SHOPPING CART </a></li>
            </ul>
        <% else %>
            <ul id="login" class="nav">
                <li><%= link_to "SIGN OUT", signout_path, method: "delete" %></li>
                <li> <a href="#shoppingcart" role="button" data-toggle="modal"> SHOPPING CART </a></li>
            </ul>
        <% end %>
    </div>
</div>

app/views/shared/_nav_form.html.erb
      <!-- Shopping Cart Modal -->
       <div id="shoppingcart" class="modal hide fade">
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h3 class="title_modal">YOUR CART</h3>
              </div>
              <div class="modal-body">
                <form id="shoppingcart" name="frmModal" method="post">
                  <table>
                     <tbody>
                      <tr>

                        <td class="c">
                          <p> Brown Oxford</p>
                        </td>
                        </td>

                        <td class="c">
                          <p> 1 </p>
                        </td>

                        <td class="c">
                          <p> $300 </p>
                        </td>

                        <td class="c">
                          <a href="#"> Remove</a>
                        </td>
                      </tr>
                     </tbody> 
                    </table>
                 </form>
              </div>
              <div class="modal-footer">
                  <%= link_to "Check Out", checkout_path, class: "home_button" %>
              </div>
         </div>